name: peek
version: '0.9.1+git'
icon: data/icons/512x512/com.uploadedlobster.peek.png
summary: Simple animated GIF screen recorder with an easy to use interface
description: |
  Peek creates animated GIF screencasts using FFmpeg and ImageMagick. It was
  built for the specific use case of recording screen areas, e.g., for easily
  showing UI features of your own apps or for showing a bug in bug reports. It
  is not a general purpose screencast app with extended features and it never
  will be.
grade: stable
confinement: strict

apps:
  peek:
    command: desktop-launch launch-peek
    desktop: usr/share/applications/com.uploadedlobster.peek.desktop
    plugs:
      - x11
      - home
      - gsettings

slots:
  session-dbus-interface:
    interface: dbus
    name: com.uploadedlobster.peek
    bus: session

parts:
  peek:
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DGSETTINGS_COMPILE=OFF
    source: .
    after:
      - desktop-gtk3
    build-packages:
      - libgtk-3-dev
      - libkeybinder-3.0-dev
      - gettext
      - valac
    stage-packages:
      - libcanberra-gtk3-module
      - libkeybinder-3.0-0
    install: |
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
    prime:
      - -usr/share/doc
      - -usr/share/man

  launcher:
    plugin: dump
    source: data/snapcraft/
    organize:
      launch-peek: bin/launch-peek
    install: |
      chmod 0555 $SNAPCRAFT_PART_INSTALL/launch-peek

  ffmpeg:
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-3.2.4.tar.xz
    configflags:
      - --disable-debug
      - --disable-static
      - --enable-gpl
      - --enable-libvpx
      - --enable-libx264
      - --enable-shared
      - --enable-x11grab
      - --disable-ffplay
      - --disable-ffprobe
      - --disable-ffserver
      - --disable-doc
      - --disable-everything
      - --enable-decoder=h264
      - --enable-decoder=rawvideo
      - --enable-encoder=libx264
      - --enable-encoder=libx264rgb
      - --enable-encoder=libvpx_vp8
      - --enable-encoder=rawvideo
      - --enable-encoder=pam
      - --enable-parser=h264
      - --enable-demuxer=avi
      - --enable-muxer=avi
      - --enable-muxer=mp4
      - --enable-muxer=webm
      - --enable-muxer=rawvideo
      - --enable-filter=crop
      - --enable-filter=scale
      - --enable-protocol=file
      - --enable-indev=x11grab_xcb
    build-packages:
      - libx264-dev
    prime:
      - -usr/share/applications
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/locale
      - -usr/share/man

  imagemagick:
    plugin: autotools
    source: https://www.imagemagick.org/download/ImageMagick-6.9.7-10.tar.bz2
    configflags:
      - --enable-static=no
      - --disable-docs
      - --without-gvc
      - --without-djvu
      - --without-autotrace
      - --without-jbig
      - --without-fpx
      - --without-dps
      - --without-fftw
      - --without-png
      - --without-pango
      - --without-jpeg
      - --without-tiff
      - --without-webp
      - --without-wmf
      - --without-raqm
      - --without-xml
      - --without-openjp2
      - --without-openexr
      - --without-freetype
      - --without-fontconfig
      - --without-magick-plus-plus
    prime:
      - -usr/bin/ffplay
      - -usr/bin/ffprobe
      - -usr/bin/ffserver
      - -usr/bin/qt-faststart
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/locale
      - -usr/share/man
    install: |
      if [ ! -f $SNAPCRAFT_PART_INSTALL/usr/bin/convert ]; then
        cd $SNAPCRAFT_PART_INSTALL/usr/bin
        ln -s ./convert-im6 convert
      fi
