#!/bin/bash

# Necessary for GTK, otherwise it will try to access global /etc
if [ -z "$XDG_CONFIG_DIRS" ]
then
  XDG_CONFIG_DIRS=/etc/xdg
fi
export XDG_CONFIG_DIRS=$SNAP/etc:$XDG_CONFIG_DIRS

if [ -z "$XDG_DATA_DIRS" ]
then
  XDG_DATA_DIRS=/usr/local/share/:/usr/share/
fi
export XDG_DATA_DIRS=$SNAP/share:$XDG_DATA_DIRS

peek
